### ISSUE TITLE
Should RedisClient::TimeoutError descend from Timeout::Error?

### ISSUE THREAD

**Issue by mperham** [redis-rb/redis-client#19]
Seems weird to raise network timeout errors which are not catchable by a standard `rescue Timeout::Error`. Does it make sense to extend Ruby's timeout error to gain compatibility? Or maybe just raise Timeout::Error directly? Is there a benefit to defining your own class vs reusing stdlib errors?

**Comment by casperisfine** [comment]
> Is there a benefit to defining your own class vs reusing stdlib errors?

Yes, the benefit is to have one base error, so that if you wish to handle any possible redis error `rescue RedisClient::Error` is all you need. In my mind there's nothing worse than APIs that leaks underlying exceptions (e.g. `net/http` leaks [a stupid amount of errors](https://github.com/Shopify/semian/blob/5549278a425d579a1ccd969f644bd045a9b3d62e/lib/semian/net_http.rb#L35-L44)).

It can also be done using modules, but I'd rather avoid it.

Note that [`redis` does the same](https://github.com/redis/redis-rb/blob/59a2102993c32228ce46425a019a2f6e362d9abf/lib/redis/errors.rb#L36-L37).

I'm curious what advantage you find to re-using (or subclassing) stdlib errors.

**Comment by mperham** [comment]
I'm thinking of generic network error handling, e.g. `rescue Timeout::Error, Errno::ETIMEOUT`. I don't have a real-world usecase here but I feel a bit of redundancy in the code. I'm not sure about the right thing to do but I'm also ok with you closing this if you don't feel the same.
