### ISSUE TITLE
Is it possible to bump rexml to 3.3.9?

### ISSUE THREAD

**Issue by dimitrisdovinos** [redis-rb/redis-client#218]
We are picking up HIGH severity vulnerabilities from rexml 3.2.6 CVE-2024-41124, CVE-2024-41946, CVE-2024-49761.

Is it possible to raise the rexml version above 3.3.9? At that version all 3 vulnerabilities are fixed.

**Comment by byroot** [comment]
redis-client doesn't depend on rexml. It's only development dependency brought up by rubocop.

I'll see if I can upgrade it to appease your CVE tracker, but I suspect I won't be able to because newer rubocop releases don't support as old rubies as `redis-client`.

So I'd suggest to see with whoever is sending you these vulnerabilty and tell them their tool is broken.

**Comment by byroot** [comment]
Seems you're lucky, the rexml dependency from rubocop is fairly lax: https://github.com/redis-rb/redis-client/commit/3a4f627155787c20e2a3d9e7f434cd98acf6c940

**Comment by dimitrisdovinos** [comment]
Much appreciated!
