### ISSUE TITLE
Just a reminder: maybe remove Gemfile.lock from git

### ISSUE THREAD

**Issue by liijunwei** [redis-rb/redis-client#36]
sorry about posting an issue, as there is no `discussions` tab available;

I'v seen many gems don't check `Gemfile.lock` into git, I suppose this gem probably should do the same.

Glad to see your work on this gem 👍

**Comment by byroot** [comment]
Hi, 

What you suggest used to be best practice a few years back, but that's no longer the case today. The reason is that it cause different contributors to end up with different gem versions which can cause weird problem.

Instead the new recommended thing is to commit the Gemfile.lock and either delete it on CI to fetch the latest dependencies or to setup something like dependabot to keep dependencies up to date.

I'll leave this open because I indeed didn't do the later and I should.

**Comment by liijunwei** [comment]
Thanks for replying, I didn't know "it's no longer the case today" before you told me... 😱

Let me update my knowledge a little

**Comment by liijunwei** [comment]
From bundler FAQ: [Using Gemfiles inside gems](https://bundler.io/guides/faq.html#using-gemfiles-inside-gems)

Thanks for pointing out my outdated knowledge
