### ISSUE TITLE
Mocking redis client in tests

### ISSUE THREAD

**Issue by khataev** [redis-rb/redis-client#68]
Hello!

Is there a possibility or existing gem (I haven't found it so far) which allows to mock real interaction with redis in tests when using redis-client? Analogous to [fakeredis](https://github.com/guilleiguaran/fakeredis) or [mok_redis](https://github.com/sds/mock_redis) for [redis-rb](https://github.com/redis/redis-rb).

Thanks in advance.

**Comment by byroot** [comment]
No there isn't AFAIK, and I wouldn't recommend it.

**Comment by khataev** [comment]
@byroot why don't you recommend it?

**Comment by byroot** [comment]
Because:

  - Redis is fast enough that it doesn't make a big difference
  - There will always be some small differences between fake_redis and a real redis.

Hence why I never used `fake_redis` and consort, and always removed it from projects I inherited and I'm not interested in implementing something similar for `redis-client`.

But folks who feel strongly about it are welcome to do it.

If you really want to do this, you can probably implement a "fake_redis" driver.

**Comment by guilleiguaran** [comment]
Hi! I'm the (ex-)maintainer of fakeredis, I agree with @byroot on this. Back when the project started 12 years ago it was convenient and useful since Redis wasn't widely available on all the CI platforms and tools like Docker didn't exist back then, nowadays using a real Redis instance is trivial.

I would strongly recommend using a real Redis instance instead of fakeredis, IMO it doesn't worth investing a significant amount of time migrating the mocking libraries to use redis-client and if I don't receive any PR for it I'll mark the project as deprecated.

**Comment by myxoh** [comment]
To add to that - mocking redis also means redis shares the same clock as ruby. One of the biggest benefits in my experience to using mock redis is being able to leverage `travel_to` and test behaviour that may rely on Redis expirationin a simple unit test.

**Comment by dgmora** [comment]
Up until now for rails the only required external dependency was a database, now this is adding a second one. It's doable, but this is asking many devs to have a running redis locally and in CI. It is much easier to add a fake redis as a gem. I understand the lack of interest in providing a mock, but I would very much prefer having a fake.
